/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ItineraryIdRouteImport } from './routes/itinerary.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIdRoute = ItineraryIdRouteImport.update({
  id: '/itinerary/$id',
  path: '/itinerary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/plan': typeof PlanRoute
  '/recommendations': typeof RecommendationsRoute
  '/scanner': typeof ScannerRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/plan': typeof PlanRoute
  '/recommendations': typeof RecommendationsRoute
  '/scanner': typeof ScannerRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/plan': typeof PlanRoute
  '/recommendations': typeof RecommendationsRoute
  '/scanner': typeof ScannerRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/auth'
    | '/dashboard'
    | '/plan'
    | '/recommendations'
    | '/scanner'
    | '/itinerary/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/auth'
    | '/dashboard'
    | '/plan'
    | '/recommendations'
    | '/scanner'
    | '/itinerary/$id'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/auth'
    | '/dashboard'
    | '/plan'
    | '/recommendations'
    | '/scanner'
    | '/itinerary/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PlanRoute: typeof PlanRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ScannerRoute: typeof ScannerRoute
  ItineraryIdRoute: typeof ItineraryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$id': {
      id: '/itinerary/$id'
      path: '/itinerary/$id'
      fullPath: '/itinerary/$id'
      preLoaderRoute: typeof ItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PlanRoute: PlanRoute,
  RecommendationsRoute: RecommendationsRoute,
  ScannerRoute: ScannerRoute,
  ItineraryIdRoute: ItineraryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
